# Generated by Django 4.2.11 on 2025-04-15 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
